language: bash

services:
- docker

env:
- BASE_IMAGE_STABILITY_TAG=4.12.5
- MATOMO_VER=3.11.0 TAGS=3.11,3,latest

script:
- travis_retry make && make test

after_success:
- . "${TRAVIS_BUILD_DIR}/release.sh"

notifications:
  email:
    recipients:
    - travisci@wodby.com
    on_success: never
    on_failure: always
