language: bash

services:
  - docker

env:
  global:
    - BASE_IMAGE_STABILITY_TAG=4.11.3
  matrix:
    - MATOMO_VER=3.8.1 TAGS=3.8,3,latest

script:
  - travis_retry make && make test

after_success:
  - . "${TRAVIS_BUILD_DIR}/release.sh"
