language: bash

services:
  - docker

env:
  global:
    - LATEST_TAG=3.3
    - BASE_IMAGE_STABILITY_TAG=4.2.0
  matrix:
    - TAG=3.3 MATOMO_VER=3.3.0 PHP_VER=7.1 EXTRA_TAG=3

script:
  - travis_retry make && make test

after_success:
  - bash "${TRAVIS_BUILD_DIR}/travis_release"
