language: bash

services:
- docker

env:
  global:
  - BASE_IMAGE_STABILITY_TAG=4.14.3
  - MATOMO_VER=3.13.2 TAGS=3.13,3,latest

script:
- travis_retry make && make test

after_success:
- . "${TRAVIS_BUILD_DIR}/release.sh"

notifications:
  email:
    recipients:
    - travisci@wodby.com
    on_success: never
    on_failure: always
