language: bash

services:
  - docker

env:
  global:
    - BASE_IMAGE_STABILITY_TAG=4.7.4
  matrix:
    - MATOMO_VER=3.6.1 TAGS=3.6,3,latest

script:
  - travis_retry make && make test

after_success:
  - . "${TRAVIS_BUILD_DIR}/release.sh"
