language: bash

services:
  - docker

env:
  global:
    - BASE_IMAGE_STABILITY_TAG=4.8.2
  matrix:
    - MATOMO_VER=3.7.0 TAGS=3.7,3,latest

script:
  - travis_retry make && make test

after_success:
  - . "${TRAVIS_BUILD_DIR}/release.sh"
