language: bash

services:
  - docker

env:
  global:
    - BASE_IMAGE_STABILITY_TAG=4.5.2
    - MATOMO_VER=3.5.1 TAGS=3.5,3,latest

script:
  - travis_retry make && make test

after_success:
  - . "${TRAVIS_BUILD_DIR}/release.sh"
