language: bash

services:
  - docker

env:
  global:
    - LATEST_TAG=3.3
  matrix:
    - TAG=3.3 MATOMO_VER=3.3.0 EXTRA_TAG=3

script:
  - travis_retry make && make test

after_success:
  - bash "${TRAVIS_BUILD_DIR}/travis_release"
