name: Build
description: Build matomo image
inputs:
  version:
    description: version
    required: true
  php_ver:
    description: php version
    required: true
  tags:
    description: image tags
    required: true
runs:
  using: "composite"
  steps:
  - name: Build image
    env:
      MATOMO_VER: ${{ inputs.version }}
      PHP_VER: ${{ inputs.php_ver }}
      TAGS: ${{ inputs.tags }}
    run: |
      set -e
      make
      make test
      . $GITHUB_ACTION_PATH/release.sh
    shell: bash
