name: Build docker image

on:
  push:
    branches:
    - master

    tags:
    - '*'

env:
  BASE_IMAGE_STABILITY_TAG: 4.30.0
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  matomo-4:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/actions
      with:
        version: '4.9.0'
        php_ver: 8.1
        tags: 4.9,4,latest
        alpine_ver: 3.15
  matomo-4-alpine313:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/actions
      with:
        version: '4.9.0'
        php_ver: 8.1
        tags: 4.9-alpine3.13,4-alpine3.13,alpine3.13
        alpine_ver: 3.13