name: Build docker image

on:
  push:
    branches:
    - master

    tags:
    - '*'

env:
  BASE_IMAGE_STABILITY_TAG: 4.17.4

jobs:
  matomo-3:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/actions
      with:
        version: 3.14.1
        php_ver: 7.2
        tags: 3.14,3,latest
        base_image_stability_tag: ${{ env.BASE_IMAGE_STABILITY_TAG }}
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
